# cotire.cmake 1.7.8 generated file
# /Users/erikwijmans/Projects/c++/buid/placeScan/placeScan_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/Users/erikwijmans/Projects/c++/CMake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.8")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_FLAGS_NONE "-std=gnu++14;-O3;-g;-fopenmp")
set (COTIRE_TARGET_CONFIGURATION_TYPES "None")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/Users/erikwijmans/Projects/c++")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_NONE "/opt/local/include;/Users/erikwijmans/Projects/c++/globals;/Library/gurobi651/mac64/include;/usr/local/include/opencv;/usr/local/include")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/Users/erikwijmans/Projects/c++/placeScan/placeScan.cpp;/Users/erikwijmans/Projects/c++/placeScan/placeScanHelper.cpp;/Users/erikwijmans/Projects/c++/placeScan/placeScanHelper2.cpp;/Users/erikwijmans/Projects/c++/placeScan/multiLabeling.cpp;/Users/erikwijmans/Projects/c++/placeScan/panoramaMatcher.cpp;/Users/erikwijmans/Projects/c++/placeScan/highOrder.cpp;/Users/erikwijmans/Projects/c++/placeScan/doorDetector.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "")
set (CMAKE_CXX_COMPILER_ID "AppleClang")
set (CMAKE_CXX_COMPILER_VERSION "8.0.0.8000038")
set (CMAKE_CXX_COMPILER "/usr/local/bin/clang++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_FRAMEWORK_SEARCH_FLAG "-F")
set (CMAKE_CXX_SYSTEM_FRAMEWORK_SEARCH_FLAG "-iframework ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
